import { compile } from '@xaendar/compiler';
import { basename, dirname, extname, resolve } from 'node:path';
import type { Plugin } from 'vite';
import { COMPONENT_FILE_RE, TEMPLATE_EXTENSION } from './costants.js';
import { NodeCompilerHost } from './node-compiler-host.model.js';

/**
 * Vite plugin that compiles Xaendar DSL template files (`.xd.component.html`)
 * and injects the generated render methods into the associated component class.
 *
 * ## Dev mode
 *
 * Files are transformed on demand when the browser requests them. The plugin
 * registers the template as a watch file via `this.addWatchFile` so that
 * modifying the template invalidates the component module and triggers HMR.
 *
 * ## Production build
 *
 * The same `transform` hook runs for every component file during the esbuild
 * bundling phase. The output is handed to esbuild as TypeScript, which strips
 * the types and produces the final JavaScript bundle.
 *
 * @returns A Vite {@link Plugin} instance.
 *
 * @example
 * // vite.config.ts
 * import { defineConfig } from 'vite';
 * import { xaendarPlugin } from '@xaendar/build-tools';
 *
 * export default defineConfig({
 *   plugins: [xaendarPlugin()],
 * });
 */
export function xaendarPlugin(): Plugin {
  const host = new NodeCompilerHost;

  return {
    name: 'xaendar',
    transform(code, id) {
      if (!COMPONENT_FILE_RE.test(id)) {
        return null;
      }

      const templatePath = resolveTemplatePath(id);
      this.addWatchFile(templatePath);

      if (!host.fileExists(templatePath)) {
        this.warn(`Xaendar: could not find template at ${templatePath}`);
        return null;
      }

      const templateSource = host.readFile(templatePath);
      if (templateSource === undefined) {
        this.warn(`Xaendar: could not read template at ${templatePath}`);
        return null;
      }

      let compiledMethods!: string;
      try {
        compiledMethods = compile(templateSource);
      } catch (err) {
        this.error(`Xaendar: failed to compile template ${templatePath}:\n${String(err)}`);
      }

      let transformed!: string;
      try {
        transformed = fixDecoratorExport(injectRenderMethods(code, compiledMethods));
      } catch (err) {
        this.error(String(err));
      }

      return {
        code: transformed
      };
    },
  };
}

/**
 * Resolves the absolute path of the template file associated with a given
 * component `.ts` file, following the convention:
 *
 * ```
 * app.xd.component.ts  →  app.xd.component.html
 * ```
 *
 * @param componentPath - Absolute path of the component TypeScript file.
 * @returns Absolute path of the associated template file.
 */
function resolveTemplatePath(componentPath: string): string {
  const dir = dirname(componentPath);
  const base = basename(componentPath, extname(componentPath)).split('.')[0];
  return resolve(dir, `${base}${TEMPLATE_EXTENSION}`);
}

/**
 * Injects the compiled render methods into the component class source by
 * replacing the `// __XAENDAR_RENDER__` placeholder.
 *
 * Each generated function (e.g. `_render`, `control_flow_if_2`) becomes
 * a private method of the class so that `this` and `this._root` resolve
 * correctly at runtime without any additional context parameter.
 *
 * @param compiledCode - The original TypeScript source of the component file.
 * @param compiledMethods - The raw output of the compiler, already
 *   formatted as class method bodies (no `function` keyword, no standalone
 *   context parameter).
 * @returns The transformed TypeScript source with the placeholder replaced
 *   by the compiled methods.
 * @throws {Error} When the placeholder is not found in the source — this
 *   means the component file was not scaffolded correctly by the CLI.
 */
function injectRenderMethods(compiledCode: string, compiledMethods: string): string {
  const lastBraceIndex = compiledCode.lastIndexOf('}');
  if (lastBraceIndex === -1) {
    throw new Error(`Xaendar: could not find closing brace in component source. Make sure the component was generated by the Xaendar CLI.`);
  }

  const methods = compiledMethods.trim();

  return `${compiledCode.slice(0, lastBraceIndex)}\n\n${methods}\n${compiledCode.slice(lastBraceIndex)}`;
}

/**
 * esbuild bug workaround — quando transpila decorator stage 3 con export,
 * produce `export @Decorator class Foo {}` invece di
 * `@Decorator\nexport class Foo {}`.
 * Riordina i token per produrre sintassi valida.
 */
function fixDecoratorExport(code: string): string {
  return code.replace(/^export\s+(@\w+[\s\S]*?)\s+(class\s)/gm, '$1\nexport $2');
}